### ISSUE TITLE
Landing page bugs

### ISSUE THREAD

**Issue by KoliosterNikolayIliev** [DimoDimchev/My-Wallet-Project#152]
All bugs regarding landing page need to be reported here.

Please open new issues for every bug and reference it to this one.

**Comment by KoliosterNikolayIliev** [comment]
Phone Samsung Note9:

1. When filling data in open questions in the questionnaire the text area disappears
2. Twitter button at the final screen of the questionnaire is broken

**Comment by KoliosterNikolayIliev** [comment]
Mobile and desktop version:

select toggle on the questionnaire buttons is needed. Currently un - select a question is not possible.

**Comment by DimoDimchev** [comment]
- [ ] Change the page title: currently it reads 'React App'
- [ ] Change the page logo: currently it's the React logo

**Comment by Sheko1** [comment]
Phone Xiaomi Poco F3:
Same problem as Samsung Note 9 except twitter button.

**Comment by Sheko1** [comment]
Smal phones like moto g5:
pictures and questionnaire are broken

**Comment by KoliosterNikolayIliev** [comment]
Done.
