### ISSUE TITLE
Set up Campaign landing page on 3vial.io domain

### ISSUE THREAD

**Issue by vyakov** [DimoDimchev/My-Wallet-Project#36]

**Comment by smanilov** [comment]
Consider https://tailwindcss.com/ for styling.

**Comment by DimoDimchev** [comment]
Mailing list functionality implemented using MailChimp in #44

**Comment by kalinpetrovbg** [comment]
Linked with issue #25

**Comment by kalinpetrovbg** [comment]
Current preview can be found here: 
https://drive.google.com/drive/folders/10GGKSOFRLu7Mz-JiWUisggY96TDchfqh

**Comment by kalinpetrovbg** [comment]
To decide how we will do the Pop Up feature with questions. 
Will we use Mailchimp or we will switch to another solution.

**Comment by kalinpetrovbg** [comment]
Uploaded improved version of the landing page here:
https://drive.google.com/drive/folders/10GGKSOFRLu7Mz-JiWUisggY96TDchfqh     ("full-page.jpg")
